// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "273496b7-25e0-4010-bad9-6f5890f4dc4b";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onCenterArmChange();
void onGripperChange();
void onLowerArmChange();
void onNeckGripperChange();
void onUpperArmChange();

int centerArm;
int gripper;
int lowerArm;
int neckGripper;
int upperArm;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(centerArm, READWRITE, ON_CHANGE, onCenterArmChange);
  ArduinoCloud.addProperty(gripper, READWRITE, ON_CHANGE, onGripperChange);
  ArduinoCloud.addProperty(lowerArm, READWRITE, ON_CHANGE, onLowerArmChange);
  ArduinoCloud.addProperty(neckGripper, READWRITE, ON_CHANGE, onNeckGripperChange);
  ArduinoCloud.addProperty(upperArm, READWRITE, ON_CHANGE, onUpperArmChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
